<!DOCTYPE html>
<html>
<head>
    <title>Vendor Analytics Report - {{ $vendor->name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { color: #333; margin-bottom: 5px; }
        .header p { color: #666; }
        .section { margin-bottom: 25px; }
        .section h2 { color: #2c5282; border-bottom: 2px solid #2c5282; padding-bottom: 5px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th { background-color: #f7fafc; text-align: left; padding: 8px; border: 1px solid #e2e8f0; }
        td { padding: 8px; border: 1px solid #e2e8f0; }
        .summary-box { background-color: #f0fff4; border: 1px solid #9ae6b4; border-radius: 5px; padding: 15px; margin: 15px 0; }
        .footer { margin-top: 30px; text-align: center; color: #718096; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Vendor Analytics Report</h1>
        <p>{{ $vendor->name }} - Generated on {{ $date }}</p>
    </div>

    <div class="section">
        <h2>Vendor Information</h2>
        <table>
            <tr>
                <th>Name</th>
                <td>{{ $vendor->name }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ $vendor->email }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ $vendor->profile->phone ?? 'N/A' }}</td>
            </tr>
            <tr>
                <th>Location</th>
                <td>{{ $vendor->unit->name ?? 'N/A' }}</td>
            </tr>
        </table>
    </div>

    <div class="section">
        <h2>Performance Summary</h2>
        <div class="summary-box">
            <table>
                <tr>
                    <th>Total Scans</th>
                    <td>{{ number_format($data['summary']['total_scans'] ?? 0) }}</td>
                </tr>
                <tr>
                    <th>Total Revenue</th>
                    <td>KSh {{ number_format($data['summary']['total_revenue'] ?? 0, 2) }}</td>
                </tr>
                <tr>
                    <th>Average Daily Scans</th>
                    <td>{{ number_format($data['summary']['avg_daily_scans'] ?? 0, 1) }}</td>
                </tr>
                <tr>
                    <th>Top Department</th>
                    <td>{{ $data['summary']['top_department']->name ?? 'N/A' }}</td>
                </tr>
            </table>
        </div>
    </div>

    @if(isset($data['transactions']) && count($data['transactions']) > 0)
    <div class="section">
        <h2>Recent Transactions (Last 20)</h2>
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Employee</th>
                    <th>Department</th>
                    <th>Amount</th>
                    <th>Time</th>
                </tr>
            </thead>
            <tbody>
                @foreach($data['transactions']->take(20) as $transaction)
                <tr>
                    <td>{{ $transaction->meal_date }}</td>
                    <td>{{ $transaction->employee->formal_name ?? 'Unknown' }}</td>
                    <td>{{ $transaction->employee->department->name ?? 'N/A' }}</td>
                    <td>KSh {{ number_format($transaction->amount, 2) }}</td>
                    <td>{{ $transaction->meal_time }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    @endif

    <div class="footer">
        <p>Report generated by Meal Management System</p>
        <p>Date Range: {{ $data['date_range']['start']->format('Y-m-d') }} to {{ $data['date_range']['end']->format('Y-m-d') }}</p>
    </div>
</body>
</html>
