<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Employee Scan Data Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
            border-bottom: 2px solid #333;
            padding-bottom: 10px;
        }
        .header h1 {
            margin: 0;
            font-size: 18px;
        }
        .info {
            margin-bottom: 20px;
        }
        .info table {
            width: 100%;
        }
        .info td {
            padding: 3px;
        }
        table.data {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        table.data th, table.data td {
            border: 1px solid #ddd;
            padding: 6px;
            text-align: left;
        }
        table.data th {
            background-color: #f2f2f2;
            font-weight: bold;
        }
        .summary {
            margin-bottom: 20px;
            padding: 10px;
            background-color: #f9f9f9;
            border: 1px solid #ddd;
        }
        .signature {
            margin-top: 30px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
        }
        .signature table {
            width: 100%;
            margin-top: 20px;
        }
        .signature td {
            padding: 20px 10px;
        }
        .footer {
            text-align: center;
            font-size: 10px;
            color: #666;
            margin-top: 30px;
        }
        .text-right {
            text-align: right;
        }
        .text-center {
            text-align: center;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>EMPLOYEE SCAN DATA REPORT</h1>
        <p>Period: {{ $start_date }} to {{ $end_date }}</p>
    </div>

    <div class="info">
        <table>
            <tr>
                <td width="50%"><strong>Generated On:</strong> {{ $generated_at }}</td>
                <td width="50%"><strong>Generated By:</strong> {{ $generated_by }}</td>
            </tr>
        </table>
    </div>

    <div class="summary">
        <h3>Summary</h3>
        <table style="width: auto;">
            <tr>
                <td><strong>Total Employees with Scans:</strong></td>
                <td>{{ count(array_filter($employees, function($e) { return $e['total_scans'] > 0; })) }}</td>
            </tr>
            <tr>
                <td><strong>Total Normal Scans:</strong></td>
                <td>{{ $totals['total_normal_scans'] }}</td>
            </tr>
            <tr>
                <td><strong>Total Reward Scans:</strong></td>
                <td>{{ $totals['total_reward_scans'] }}</td>
            </tr>
            <tr>
                <td><strong>Total Scans:</strong></td>
                <td>{{ $totals['total_scans'] }}</td>
            </tr>
            <tr>
                <td><strong>Total Amount:</strong></td>
                <td>KES {{ number_format($totals['total_amount'], 2) }}</td>
            </tr>
        </table>
    </div>

    <h3>Employee Scan Details</h3>
    <table class="data">
        <thead>
            <tr>
                <th>#</th>
                <th>Employee Name</th>
                <th>Employee Code</th>
                <th>Department</th>
                <th>Unit</th>
                <th class="text-center">Normal Scans</th>
                <th class="text-center">Reward Scans</th>
                <th class="text-center">Total Scans</th>
                <th class="text-right">Total Amount</th>
                <th class="text-center">Signature</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $index => $employee)
            <tr>
                <td class="text-center">{{ $index + 1 }}</td>
                <td>{{ $employee['employee_name'] }}</td>
                <td>{{ $employee['employee_code'] }}</td>
                <td>{{ $employee['department'] }}</td>
                <td>{{ $employee['unit'] }}</td>
                <td class="text-center">{{ $employee['normal_scans'] }}</td>
                <td class="text-center">{{ $employee['reward_scans'] }}</td>
                <td class="text-center">{{ $employee['total_scans'] }}</td>
                <td class="text-right">KES {{ number_format($employee['total_amount'], 2) }}</td>
                <td class="text-center">_________</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="signature">
        <h3>Authorization</h3>
        <table>
            <tr>
                <td width="33%">
                    <strong>Prepared By:</strong><br>
                    _________________________<br>
                    Name: ___________________<br>
                    Date: ___________________
                </td>
                <td width="33%">
                    <strong>Verified By:</strong><br>
                    _________________________<br>
                    Name: ___________________<br>
                    Date: ___________________
                </td>
                <td width="33%">
                    <strong>Approved By:</strong><br>
                    _________________________<br>
                    Name: ___________________<br>
                    Date: ___________________
                </td>
            </tr>
        </table>
    </div>

    <div class="footer">
        This report is system-generated and requires authorized signature for validation.
    </div>
</body>
</html>
