<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Invoice {{ $invoice->invoice_number }}</title>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 800px; margin: 0 auto; padding: 20px; }
        .header { border-bottom: 2px solid #2596be; padding-bottom: 20px; margin-bottom: 30px; }
        .company-info { float: right; text-align: right; }
        .invoice-info { margin-bottom: 30px; }
        .table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .table th { background-color: #f3f4f6; text-align: left; padding: 10px; border: 1px solid #e5e7eb; }
        .table td { padding: 10px; border: 1px solid #e5e7eb; }
        .total-section { margin-top: 30px; text-align: right; }
        .total-amount { font-size: 24px; font-weight: bold; color: #2596be; }
        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 12px; font-weight: 600; }
        .badge-pending { background-color: #fef3c7; color: #92400e; }
        .badge-paid { background-color: #d1fae5; color: #065f46; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1 style="color: #2596be; margin: 0;">QR Feeding System</h1>
            <div class="company-info">
                <p><strong>REEDS Africa Talent Gateway</strong></p>
                <p>Nairobi, Kenya</p>
                <p>Email: info@reedsafrica.com</p>
            </div>
            <div style="clear: both;"></div>
        </div>

        <div class="invoice-info">
            <h2>INVOICE</h2>
            <p><strong>Invoice #:</strong> {{ $invoice->invoice_number }}</p>
            <p><strong>Period:</strong> {{ $invoice->period_start->format('F j, Y') }} - {{ $invoice->period_end->format('F j, Y') }}</p>
            <p><strong>Date:</strong> {{ $invoice->invoice_date->format('F j, Y') }}</p>
            <p><strong>Due Date:</strong> {{ $invoice->due_date->format('F j, Y') }}</p>
            <p><strong>Status:</strong> <span class="badge badge-{{ $invoice->status }}">{{ strtoupper($invoice->status) }}</span></p>
        </div>

        <div>
            <h3>Vendor Information</h3>
            <p><strong>{{ $vendor->name }}</strong></p>
            <p>Email: {{ $vendor->email }}</p>
            <p>Phone: {{ $vendor->profile->phone ?? 'N/A' }}</p>
            @if($vendor->profile && $vendor->profile->business_name)
                <p>Business: {{ $vendor->profile->business_name }}</p>
            @endif
        </div>

        <h3>Transaction Summary</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Description</th>
                    <th>Scans</th>
                    <th>Rate (Ksh)</th>
                    <th>Amount (Ksh)</th>
                </tr>
            </thead>
            <tbody>
                @foreach($invoice->items as $item)
                <tr>
                    <td>{{ $item->date->format('M j, Y') }}</td>
                    <td>{{ $item->description ?? 'Meal transactions' }}</td>
                    <td>{{ $item->scans }}</td>
                    <td>{{ number_format($item->rate, 2) }}</td>
                    <td>{{ number_format($item->amount, 2) }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>

        <div class="total-section">
            <p><strong>Total Scans:</strong> {{ $invoice->total_scans }}</p>
            <p><strong>Subtotal:</strong> Ksh {{ number_format($invoice->total_amount, 2) }}</p>
            <p><strong>Tax (0%):</strong> Ksh 0.00</p>
            <p class="total-amount">Total: Ksh {{ number_format($invoice->total_amount, 2) }}</p>
        </div>

        <div>
            <h3>Payment Instructions</h3>
            <p>Please make payment to:</p>
            <p><strong>Bank:</strong> [Bank Name]<br>
               <strong>Account Name:</strong> REEDS Africa Talent Gateway<br>
               <strong>Account Number:</strong> [Account Number]<br>
               <strong>Reference:</strong> {{ $invoice->invoice_number }}
            </p>
            <p>Payment is due within 30 days of invoice date.</p>
        </div>

        <div class="footer">
            <p>This is an automated invoice generated by the QR Feeding System.</p>
            <p>If you have any questions about this invoice, please contact accounting@reedsafrica.com</p>
            <p>© {{ date('Y') }} REEDS Africa Talent Gateway. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
